version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: oauth2
      MYSQL_ROOT_PASSWORD: marcosph
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - 192.168.0.7
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.0.7:3306/oauth2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: marcosph

volumes:
  db_data: